from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from models.reviews import ReviewModel

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://localhost/galvanize_snacks_python_api'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

review1 = ReviewModel( 1, "Incredible!", "If it were a person I'd say to it: Is your name Dan Druff? You get into people's hair. I mean like, I'd say that you're funny but looks aren't everything.", 1, 1 )
review2 = ReviewModel( 2, "Tasty!", "If it were a person I'd say to this snack: I appreciate all of your opinions. I mean like, You have ten of the best fingers I have ever seen!", 3, 2 )
review3 = ReviewModel( 3, "Tasty!", "If it were a person I'd say to it: Learn from your parents' mistakes - use birth control! I mean like, I thought of you all day today. I was at the zoo.", 2, 3 )
review4 = ReviewModel( 4, "Refined!", "If it were a person I'd say to this snack: I would share my dessert with you. I mean like, You are a champ!", 5, 4 )
review5 = ReviewModel( 5, "Ergonomic!", "If it were a person I'd say to it: It looks like your face caught on fire and someone tried to put it out with a hammer. I mean like, You're so fat your belly button has an echo echo echo...", 1, 5 )
review6 = ReviewModel( 6, "Refined!", "If it were a person I'd say to this snack: We would enjoy a cookout with you! I mean like, You are the rare catalyst to my volatile compound.", 4, 6 )
review7 = ReviewModel( 7, "Small!", "If it were a person I'd say to it: You're so fat your shadow casts a shadow. I mean like, You may not be the best looking girl here, but beauty is only a light switch away!", 2, 7 )
review8 = ReviewModel( 8, "Intelligent!", "If it were a person I'd say to this snack: There isn't a thing about you that I don't like. I mean like, You will still be beautiful when you get older.", 2, 8 )
review9 = ReviewModel( 9, "Practical!", "If it were a person I'd say to it: You're so dumb, your dog teaches you tricks. I mean like, I don't exactly hate you, but if you were on fire and I had water, I'd drink it.", 2, 9 )
review10 = ReviewModel( 10, "Ergonomic!", "If it were a person I'd say to this snack: You are the gravy to my mashed potatoes. I mean like, Will you sign my yearbook?", 5, 10 )
review11 = ReviewModel( 11, "Incredible!", "If it were a person I'd say to it: You are proof that evolution CAN go in reverse. I mean like, Even if you were twice as smart, you'd still be stupid!", 2, 11 )
review12 = ReviewModel( 12, "Ergonomic!", "If it were a person I'd say to this snack: You make babies smile. I mean like, You're so rad.", 3, 12 )
review13 = ReviewModel( 13, "Fantastic!", "If it were a person I'd say to it: Your ears are so big when you stand on a mountain they look like trophy handles. I mean like, I wish you no harm, but it would have been much better if you had never lived.", 1, 13 )
review14 = ReviewModel( 14, "Refined!", "If it were a person I'd say to this snack: I would enjoy a roadtrip with you. I mean like, You have very smooth hair.", 5, 14 )
review15 = ReviewModel( 15, "Tasty!", "If it were a person I'd say to it: Shut up, you'll never be the man your mother is. I mean like, Ever since I saw you in your family tree, I've wanted to cut it down.", 2, 15 )
review16 = ReviewModel( 16, "Licensed!", "If it were a person I'd say to this snack: Don't worry. You'll do great. I mean like, Don't worry about procrastinating on your studies, I know you'll do great!", 7, 16 )
review17 = ReviewModel( 17, "Awesome!", "If it were a person I'd say to it: Nice tan, orange is my favorite color. I mean like, Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology.", 2, 17 )
review18 = ReviewModel( 18, "Practical!", "If it were a person I'd say to this snack: Your skin is radiant. I mean like, You look so perfect.", 5, 18 )
review19 = ReviewModel( 19, "Generic!", "If it were a person I'd say to it: What are you doing here? Did someone leave your cage open? I mean like, You're so ugly, when you popped out the doctor said \"Aww what a treasure\" and your mom said \"Yeah, lets bury it.\"", 1, 19 )
review20 = ReviewModel( 20, "Fantastic!", "If it were a person I'd say to this snack: I like those shoes more than mine. I mean like, You're nicer than a day on the beach.", 4, 20 )
review21 = ReviewModel( 21, "Small!", "If it were a person I'd say to it: It's better to keep your mouth shut and give the 'impression' that you're stupid than to open it and remove all doubt. I mean like, You are proof that God has a sense of humor.", 2, 21 )
review22 = ReviewModel( 22, "Small!", "If it were a person I'd say to this snack: I heard you make really good French Toast. I mean like, I'd wake up for an 8 a.m. class just so I could sit next to you.", 5, 22 )
review23 = ReviewModel( 23, "Incredible!", "If it were a person I'd say to it: If what you don't know can't hurt you, you're invulnerable. I mean like, Are you always an idiot, or just when I'm around?", 1, 23 )
review24 = ReviewModel( 24, "Sleek!", "If it were a person I'd say to this snack: I would do your taxes any day. I mean like, You deserve a promotion.", 4, 24 )
review25 = ReviewModel( 25, "Handmade!", "If it were a person I'd say to it: The best part of you is still running down your old mans leg. I mean like, I was pro life before I met you.", 2, 25 )
review26 = ReviewModel( 26, "Rustic!", "If it were a person I'd say to this snack: Take a break; you've earned it. I mean like, I don't speak much English, but with you all I really need to say is beautiful.", 4, 26 )
review27 = ReviewModel( 27, "Tasty!", "If it were a person I'd say to it: Keep talking, someday you'll say something intelligent! I mean like, Your dad's condom is a bigger than your personality.", 1, 27 )
review28 = ReviewModel( 28, "Gorgeous!", "If it were a person I'd say to this snack: I heard you make really good French Toast. I mean like, I love what you've done with the place.", 5, 28 )
review29 = ReviewModel( 29, "Fantastic!", "If it were a person I'd say to it: I could eat a bowl of alphabet soup and shit out a smarter statement than that. I mean like, It's kinda sad watching you attempt to fit your entire vocabulary into a sentence.", 1, 29 )
review30 = ReviewModel( 30, "Handmade!", "If it were a person I'd say to this snack: Treat yourself to another compliment! I mean like, You smell nice.", 5, 30 )
review31 = ReviewModel( 31, "Gorgeous!", "If it were a person I'd say to it: If brains were dynamite you wouldn't have enough to blow your nose. I mean like, You do realize makeup isn't going to fix your stupidity?", 2, 31 )
review32 = ReviewModel( 32, "Tasty", "If it were a person I'd say to it: What are you going to do for a face when the baboon wants his butt back? I mean like, You are depriving some poor village of its idiot.", 2, 1 )
review33 = ReviewModel( 33, "Practical", "If it were a person I'd say to this snack: Shall I compare thee to a summer's day?  Thou art more lovely and more temperate. I mean like, Your body fat percentage is perfectly suited for your height.", 4, 2 )
review34 = ReviewModel( 34, "Awesome", "If it were a person I'd say to it: If I wanted to hear from an asshole, I'd fart. I mean like, I heard you went to a haunted house and they offered you a job.", 1, 3 )
review35 = ReviewModel( 35, "Small", "If it were a person I'd say to this snack: You and Chuck Norris are on equal levels. I mean like, You make the gloomy days a little less gloomy.", 3, 4 )
review36 = ReviewModel( 36, "Small", "If it were a person I'd say to it: I was pro life before I met you. I mean like, You're as useful as an ashtray on a motorcycle.", 1, 5 )
review37 = ReviewModel( 37, "Licensed", "If it were a person I'd say to this snack: You look great in this or any other light. I mean like, Your cooking reminds me of my mother's.", 4, 6 )
review38 = ReviewModel( 38, "Gorgeous", "If it were a person I'd say to it: You're so ugly, the only dates you get are on a calendar. I mean like, A sharp tongue is no indication of a keen mind.", 1, 7 )
review39 = ReviewModel( 39, "Sleek", "If it were a person I'd say to this snack: <3 I mean like, You're more cuddly than the Downy Bear.", 4, 8 )
review40 = ReviewModel( 40, "Licensed", "If it were a person I'd say to it: You must have a Teflon brain, because nothing sticks. I mean like, Your ambition outweighs your relevant skills.", 2, 9 )
review41 = ReviewModel( 41, "Rustic", "If it were a person I'd say to this snack: I like your socks. I mean like, You're real happening in a far out way.", 4, 10 )
review42 = ReviewModel( 42, "Unbranded", "If it were a person I'd say to it: You have the perfect face for radio. I mean like, Why don't you slip into something more comfortable -- like a coma.", 1, 11 )
review43 = ReviewModel( 43, "Unbranded", "If it were a person I'd say to this snack: If we were playing kickball, I'd pick you first. I mean like, I like your pants.", 5, 12 )
review44 = ReviewModel( 44, "Tasty", "If it were a person I'd say to it: You prefer three left turns to one right turn. I mean like, You're so ugly you have to trick or treat over the phone.", 2, 13 )
review45 = ReviewModel( 45, "Handmade", "If it were a person I'd say to this snack: Your eyebrows really make your pretty eyes stand out. I mean like, You listen to the coolest music.", 5, 14 )
review46 = ReviewModel( 46, "Gorgeous", "If it were a person I'd say to it: Your breath is so stinky, we look forward to your farts. I mean like, You must have a very low opinion of people if you think they are your equals.", 2, 15 )
review47 = ReviewModel( 47, "Gorgeous", "If it were a person I'd say to this snack: If you were around, I would enjoy doing my taxes. I mean like, You're nicer than a day on the beach.", 4, 16 )
review48 = ReviewModel( 48, "Rustic", "If it were a person I'd say to it: For those who never forget a face, you are an exception. I mean like, It's hard to get the big picture when you have such a small screen.", 1, 17 )
review49 = ReviewModel( 49, "Practical", "If it were a person I'd say to this snack: You are the star of my daydreams. I mean like, You're sweeter than than a bucket of bon-bons!", 5, 18 )
review50 = ReviewModel( 50, "Refined", "If it were a person I'd say to it: You look like a before picture. I mean like, You do realize makeup isn't going to fix your stupidity?", 2, 19 )
review51 = ReviewModel( 51, "Rustic", "If it were a person I'd say to this snack: Well done! I mean like, You would look good in glasses OR contacts.", 5, 20 )
review52 = ReviewModel( 52, "Handcrafted", "If it were a person I'd say to it: Why don't you check eBay and see if they have a life for sale. I mean like, Just reminding u there is a very fine line between hobby and mental illness.", 2, 21 )
review53 = ReviewModel( 53, "Intelligent", "If it were a person I'd say to this snack: You're the bee's knees. I mean like, Your feet are perfect size!", 1, 22 )
review54 = ReviewModel( 54, "Handcrafted", "If it were a person I'd say to it: Any similarity between you and a human is purely coincidental. I mean like, If ignorance is bliss, you must be the happiest person on earth.", 1, 23 )
review55 = ReviewModel( 55, "Refined", "If it were a person I'd say to this snack: You are a bucket of awesome. I mean like, You are infatuating.", 5, 24 )
review56 = ReviewModel( 56, "Small", "If it were a person I'd say to it: Is your ass jealous of the amount of shit that just came out of your mouth? I mean like, Your family tree must be a cactus because everybody on it is a prick.", 1, 25 )
review57 = ReviewModel( 57, "Gorgeous", "If it were a person I'd say to this snack: I would share my fruit Gushers with you. I mean like, I could hang out with you for a solid year and never get tired of you.", 1, 26 )
review58 = ReviewModel( 58, "Small", "If it were a person I'd say to it: Nice tan, orange is my favorite color. I mean like, You must have a very low opinion of people if you think they are your equals.", 2, 27 )
review59 = ReviewModel( 59, "Rustic", "If it were a person I'd say to this snack: I wish I could move your furniture. I mean like, If you were in a movie you wouldn't get killed off.", 4, 28 )
review60 = ReviewModel( 60, "Handcrafted", "If it were a person I'd say to it: Looks aren't everything; in your case, they aren't anything I mean like, Nice tan, orange is my favorite color.", 1, 29 )
review61 = ReviewModel( 61, "Tasty", "If it were a person I'd say to this snack: You are a champ! I mean like, I like those shoes more than mine.", 5, 30 )
review62 = ReviewModel( 62, "Awesome", "If it were a person I'd say to it: Your dad's condom is a bigger than your personality. I mean like, You're so fat your belly button has an echo echo echo...", 2, 31 )
review63 = ReviewModel( 63, "Bad for business", "My guards love these, but you try keeping the larder full when all of your Gamorians have the munchies!", 1, 31 )
review64 = ReviewModel( 64, "Biscotti Bliss!", "Cookie! Me want cookie!", 4, 31 )
review65 = ReviewModel( 65, "The treat that travels well", "I like 'em, and they are great at sea; they don't even need to be salt-packed!", 4, 31 )
review66 = ReviewModel( 66, "Seriously? Yuck", "I have certainly had sooooo much better.", 1, 31 )
review67 = ReviewModel( 67, "Solo! Solo! Too Nakma Noya Solo!", "Han ma boo-kee, keelee ka-lya dooka. Wadja da boolya ra Moy. Han, Mah kee cheezay. Hassatamooma koh kee malyaloongee.", 5, 31 )
review68 = ReviewModel( 68, "*Snobby Voice*", "Well I have certainly had sooooo much better.", 1, 2 )
review69 = ReviewModel( 69, "I can't have just one!", 'I love these! Not only are they yummy, but they give me that certain je ne sais quoi I need in the courage department to fight ghosts.', 5, 31 )

db.session.add_all([review1, review2, review3, review4, review5, review6, review7, review8, review9, review10, review11, review12, review13, review14, review15, review16, review17, review18, review19, review20, review21, review22, review23, review24, review25, review26, review27, review28, review29, review30, review31, review32, review33, review34, review35, review36, review37, review38, review39, review40, review41, review42, review43, review44, review45, review46, review47, review48, review49, review50, review51, review52, review53, review54, review55, review56, review57, review58, review59, review60, review61, review62, review63, review64, review65, review66, review67, review68, review69 ])

db.session.commit()
